dados <- read.csv("C:\\data_science\\codigos\\r\\dataframe\\atlas2010.csv", header = TRUE, sep = ",")
# print(dim(dados))
# print(names(dados))
# print(colnames(dados))
# print(dados$fectot)
# print(dados[2, ])
# print(dados[2, 'mort1'])
selecao = subset(dados, mort1 > 40)
# plot(dados$mort1, dados$fectot)
# plot(selecao$mort1, selecao$fectot)
selecao2 = subset(dados, mort1 > 40 | mort5 > 40)
plot(selecao2$mort1, selecao2$fectot)